version: '3'

services: 
    es01:
        #image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        build:
            context: elasticsearch
            dockerfile: Dockerfile
        #container_name: es01
        hostname: es01
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - rede
    
    kibana:
        #image: docker.elastic.co/kibana/kibana:7.11.2
        build:
            context: kibana
            dockerfile: Dockerfile
        #container_name: kibana
        #container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
        networks:
            - rede
        depends_on:
            - es01

#    nginx1:
#        build:
#            context: nginx1
#            dockerfile: Dockerfile
#        depends_on:
#            - es01
#            - kibana
#        ports:
#            - 9000:80
#        networks:
#            - rede
#
#
#    nginx2:
#        build:
#            context: nginx2
#            dockerfile: Dockerfile
#        depends_on:
#            - es01
#            - kibana
#        ports:
#            - 9001:80
#        networks:
#            - rede

    nginx3:
        build:
            context: nginx3
            dockerfile: Dockerfile
        depends_on:
            - es01
            - kibana
        ports:
            - 9002:80
        networks:
            - rede

    tomcat9:
        build:
            context: tomcat9
            dockerfile: Dockerfile
        container_name: tomcat9
        hostname: tomcat9server
        depends_on:
            - es01
            - kibana
        ports:
            - 9003:8080
        networks:
            - rede


    tomcatmonitoramento:
        build:
            context: monitoramento_logs
            dockerfile: Dockerfile
        container_name: tomcatmonitoramento
        hostname: tomcatmonitoramento
        depends_on:
            - es01
            - kibana
        ports:
            - 9004:8080
        networks:
            - rede


    filebeat:
        build: log_container
        container_name: filebeat
        hostname: mydockerhost
        #restart: unless-stopped
        depends_on:
            -   es01
        environment:
            - ELASTICSEARCH_HOSTS=es01:9200
        labels:
            co.elastic.logs/enabled: "false"
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - type: bind
              source: /var/lib/docker
              target: /var/lib/docker
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "2"
        networks:
            - rede

networks:
    rede:
        external: false
volumes:
    es01: